In [26]:
# Importación módulos
import sys
import numpy as np
np.set_printoptions(threshold=10000)
import cv2 as cv
import matplotlib.pyplot as plt
%matplotlib inline

In [27]:
# Función máscara (usando bucle)
def mascara(img,mask):
    resimg = img.copy()
    for x in range(img.shape[0]):
        for y in range(img.shape[1]):
            resimg[x,y] = resimg[x,y]*mask[x,y]
    return resimg

#Función máscara (usando propiedades Numpy)
def mascara2(img,mask):
    return np.multiply(mask,img)

In [29]:
img = np.array([
        [1,1,1,3],
        [2,1,1,1],
        [3,2,1,1],
        [1,1,1,2],
    ])

mask = np.array([
        [1,0,1,1],
        [1,0,1,1],
        [1,0,1,0],
        [1,0,1,0],   
    
    ])

res = mascara(img,mask)
print(f"Resultado:\n {res} \n")

res2 = mascara2(img,mask)
print(f"Resultado (usando Numpy):\n {res2} \n")

Resultado:
 [[1 0 1 3]
 [2 0 1 1]
 [3 0 1 0]
 [1 0 1 0]] 

Resultado (usando Numpy):
 [[1 0 1 3]
 [2 0 1 1]
 [3 0 1 0]
 [1 0 1 0]] 

