In [1]:
# Importación módulos
import sys
import numpy as np
np.set_printoptions(threshold=10000)
import cv2 as cv
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
# Función filtro
def mediana(img):
    #rows, colums
    r,c = img.shape
    imgcopy = img.copy()
    resimg = np.zeros((r,c), dtype=int)
    posocho = [(-1,-1),(-1,0),(-1,+1),(0,-1),(0,0),(0,+1),(+1,-1),(+1,0),(+1,+1)] # Vecinos que puede tener un pixel en 8-adyacencia
    for x in range(1,r-1):
        for y in range(1,c-1): # Eliminamos los bordes del bucle
            pximg = np.array([imgcopy[x+i,y+j] for i,j in posocho]) # Matriz 3x3 de la seccion de la imagen
            resimg[x,y] = np.median(pximg)
    return resimg

In [3]:
img = np.array([
    [12,14,17,24,32,30],
    [19,18,17,26,36,40],
    [26,21,17,28,40,42],
    [20,19,18,26,33,35],
    [14,17,20,23,27,20],
    [35,14,22,13,40,21]
    ])

print(mediana(img))

[[ 0  0  0  0  0  0]
 [ 0 17 18 26 32  0]
 [ 0 19 19 26 35  0]
 [ 0 19 20 26 28  0]
 [ 0 19 19 23 26  0]
 [ 0  0  0  0  0  0]]


In [4]:
ruta =  '../imgpack/WorldView_1-1_PAN.png' # Consideramos que la imagen es monobanda
img2 = cv.imread(ruta,cv.IMREAD_GRAYSCALE) #Transformamos nuestra imagen a escala de grises

In [6]:
img2_exp = mediana(img2)
cv.imwrite("ResEJ3.png", img2_exp)

True