In [1]:
# Importación módulos
import sys
import numpy as np
np.set_printoptions(threshold=10000)
import cv2 as cv
import matplotlib.pyplot as plt
%matplotlib inline

In [45]:
ruta =  '../imgpack/Monobanda/2_Corsica.jpg' # Consideramos que la imagen es monobanda
img = cv.imread(ruta,cv.IMREAD_GRAYSCALE) #Transformamos nuestra imagen a escala de grises

In [71]:
# Función filtro
def filtro(img, cf):
    #rows, colums
    r,c = img.shape
    imgcopy = img.copy()
    resimg = np.zeros((r,c), dtype=int)
    posocho = [(-1,-1),(-1,0),(-1,+1),(0,-1),(0,0),(0,+1),(+1,-1),(+1,0),(+1,+1)] # Vecinos que puede tener un pixel en 8-adyacencia
    for x in range(1,r-1):
        for y in range(1,c-1): # Eliminamos los bordes del bucle
            pximg = np.array([imgcopy[x+i,y+j] for i,j in posocho]) # Matriz 3x3 de la seccion de la imagen
            resimg[x,y] = round(np.sum(cf.flatten()*pximg) / np.sum(cf)) # Modificamos el pixel siguiendo la fórmula
    return resimg

In [73]:
img = np.array([
    [12,14,17,24,32,30],
    [19,18,17,26,36,40],
    [26,21,17,28,40,42],
    [20,19,18,26,33,35],
    [14,17,20,23,27,20],
    [35,14,22,13,40,21]
    ])

cf = np.array([
        [1,1,1],
        [1,2,1],
        [1,1,1]
    ])

print(filtro(img,cf))

[[ 0  0  0  0  0  0]
 [ 0 18 20 26 33  0]
 [ 0 20 21 27 35  0]
 [ 0 19 21 26 31  0]
 [ 0 20 19 24 26  0]
 [ 0  0  0  0  0  0]]
